version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flight_booking_app
    ports:
      - "8888:8888"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    volumes:
      - ./logs:/app/logs
    networks:
      - flight_network

networks:
  flight_network: